apiVersion: v1
kind: Pod
metadata:
  name: hdfs-shield
spec:
  containers:
  - name: main
    image: hdfs-shield
    volumeMounts:
    - name: creds
      mountPath: "/opt/creds/"
      readOnly: true
  volumes:
  - name: creds
    secret:
      secretName: hdfs-shield-creds
