apiVersion: v1
kind: Pod # using pod is just a workaround for evaluation. Need better use of distributed persistent volume solution...
metadata:
  name: hello
  labels:
    app: hello
spec:
  containers:
   - name: hello
     image: busybox
     imagePullPolicy: IfNotPresent
     command: ["sleep", "1000000"]
