apiVersion: v1
kind: Pod
metadata:
  name: hdfs-shield
  labels:
    app: hdfs-shield
spec:
  containers:
  - name: main
    image: shield
    imagePullPolicy: IfNotPresent
    env:
      - name: TLS_CERT
        value: /opt/creds/shield.crt
      - name: TLS_KEY
        value: /opt/creds/shield.key
    volumeMounts:
    - mountPath: /opt/creds
      name: creds
      readOnly: true
  volumes:
  - name: creds
    secret:
      secretName: hdfs-shield-creds

---
apiVersion: v1
kind: Service
metadata:
  name: hdfs-shield-service
  labels:
    app: hdfs-shield-service
spec:
  ports:
  - port: 20000
    protocol: TCP
    nodePort: 30001
  type: NodePort
  selector:
    app: hdfs-shield


